apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-api
  namespace: hypermine-development
spec:
  replicas: 1

  selector:
    matchLabels:
      app: entity-api
  template:
    metadata:
      labels:
        app: entity-api
    spec:
      containers:
      - name: entity-api
        image: __GOOGLE_ARTIFACT_URL__/__GOOGLE_PROJECT_ID__/__GOOGLE_ARTIFACT_REPO__/enity-api-service:__LATEST_RELEASE_TAG__
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/v1/edv/state
            port: 3001
          initialDelaySeconds: 120
          periodSeconds: 30
          failureThreshold: 3

        resources:
          requests:
            memory: "2Gi"
            cpu: "4000m"
          limits:
            memory: "4Gi"
            cpu: "8000m"
        ports:
        - containerPort: __PORT__
        env:
        - name: PORT
          value: "__PORT__"
        - name: BASE_DB_PATH
          value: __BASE_DB_PATH__
        - name: DB_CONFIG
          value: __DB_CONFIG__
        - name: HID_NETWORK_RPC
          value: __HID_NETWORK_RPC__
        - name: HID_NETWORK_API
          value: __HID_NETWORK_API__
        - name: HID_NETWORK_NAMESPACE
          value: __HID_NETWORK_NAMESPACE__
        - name: EDV_BASE_URL
          value: __EDV_BASE_URL__
        - name: EDV_CONFIG_DIR
          value: __EDV_CONFIG_DIR__
        - name: EDV_DID_FILE_PATH
          value: __EDV_DID_FILE_PATH__
        - name: EDV_KEY_FILE_PATH
          value: __EDV_KEY_FILE_PATH__
        - name: MNEMONIC
          value: __MNEMONIC__
        - name: JWT_SECRET
          value: __JWT_SECRET__
        - name: GLOBAL_TXN_CONTROLLER_QUEUE
          value: __GLOBAL_TXN_CONTROLLER_QUEUE__
        - name: Tx_Query_API
          value: __Tx_Query_API__
        - name: RABBIT_MQ_URI
          value: __RABBIT_MQ_URI__
        - name: NODE_ENV
          value: __NODE_ENV__
        - name: WHITELISTED_CORS
          value: "['https://entity.hypersign.id','https://api.entity.hypersign.id','https://api.entity-test.hypersign.id','https://wallet-prajna.hypersign.id']"
        volumeMounts:
        - name: mongo
          mountPath: "/data"
      volumes:
      - name: mongo
        secret:
          secretName: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: entity-api-service
  namespace: hypermine-development
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

spec:
  type: NodePort
  selector:
    app: entity-api
  ports:
  - port: __PORT__
    targetPort: __PORT__
    protocol: TCP

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-entity
#   namespace: hypermine-development
# spec:
#   replicas: 1

#   selector:
#     matchLabels:
#       app: nginx-entity
#   template:
#     metadata:
#       labels:
#         app: nginx-entity
#     spec:
#       containers:
#         - name: nginx-entity
#           image: __GOOGLE_ARTIFACT_URL__/__GOOGLE_PROJECT_ID__/__GOOGLE_ARTIFACT_REPO__/nginx-entity:latest
#           imagePullPolicy: Always

#           resources:
#             limits:
#               memory: "256m"
#               cpu: "500m"
#           ports:
#             - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-entity-service
#   namespace: hypermine-development
#   annotations:
#     cloud.google.com/neg: '{"ingress": true}'

# spec:
#   type: NodePort
#   selector:
#     app: nginx-entity
#   ports:
#     - port: 8080
#       targetPort: 8080
#       protocol: TCP
